services:
#    home_mumpwo.example:
#        class: Home\MumpwoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    mumpwo_user.registration.form.type:
        class: Home\MumpwoBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: mumpwo_user_registration }
